H_equacio:
  M: 40
  N: 40
  T: 1
  x_min: -2
  x_max: 3
  sigma: 0.4
  r: 0.1
  grafic_no_acotat: true
  acotacions:
    explicit_call: ["-1", "3"]
    explicit_put: ["-1.5", "0.5"]
    canvi_explicit_call: ["-2", "math.log(1.5)"]
    canvi_explicit_put: ["math.log(0.3)", "math.log(1.5)"]
    cn_call: ["-1", "3"]
    cn_put: ["-1.5", "0.5"]
    canvi_cn_call: ["math.log(0.3)", "math.log(1.5)"]
    canvi_cn_put: ["math.log(0.3)", "math.log(1.5)"]

W_equacio:
  M: 100
  N: 100
  T: 1
  x_min: -2
  x_max: 3
  sigma: 0.3
  r: 0.05
  grafic_no_acotat: false
  acotacions:
    explicit_call: ["-2", "2.7"]
    explicit_put: ["-1.8", "1.2"]
    canvi_explicit_call: ["-2", "math.log(1.5)"]
    canvi_explicit_put: ["-2", "math.log(1.5)"]
    cn_call: ["-2", "0.9"]
    cn_put: ["-0.3", "1.1"]
    canvi_cn_call: ["math.log(0.3)", "math.log(1.5)"]
    canvi_cn_put: ["math.log(0.3)", "math.log(1.5)"]
